"""Rebuild the complete approved open-side frame as clean vector geometry.
Preserves artwork, title glyphs, category glyphs and rules pixels.
"""
from pathlib import Path
import io,json,re,hashlib,subprocess
import numpy as np
from PIL import Image,ImageDraw,ImageFont
import cairosvg
R=Path(__file__).resolve().parents[2]
B='#090d0e';G='#9ba6ab'
THEMES={'Orange':('#f0a000','#d48a05'),'Red':('#e21d24','#ba131c'),'Blue':('#0096ed','#0860b5'),'Saiyan':('#008b62','#006e50'),'Freestyle':('#969da0','#626b70'),'Black':('#bdc8d2','#626c7d')}
def glyph(im,box):
 c=im.crop(box);a=np.asarray(c);mask=Image.fromarray(np.clip((a.min(2).astype(float)-160)*255/75,0,255).astype('uint8'));return mask

def render(im,c):
 n=int(c['number']);a,p=THEMES.get(c['style'],THEMES['Freestyle']);g=G
 if n in (15,16):a,p,g='#d9b64f','#a18435','#c7a64c'
 title=glyph(im,(100,55,980,136));label=glyph(im,(215,774,855,826));power=glyph(Image.open(io.BytesIO(subprocess.check_output(['git','show','origin/main:public/assets/cards/saiyan-052-orange-neck-restraints.webp'],cwd=R))).convert('RGB'),(85,892,350,944))
 svg=f'''<svg xmlns="http://www.w3.org/2000/svg" width="1070" height="1470">
 <defs><linearGradient id="title" x2="0" y2="1"><stop stop-color="{a}"/><stop offset="1" stop-color="{p}"/></linearGradient></defs>
 <rect width="1070" height="166" fill="{B}"/>
 <path d="M21 48L50 20H126L146 44H924L944 20H1020L1049 48V118L1005 158H984L1025 121V72L988 33H978L966 44H104L92 33H82L45 72V121L86 158H65L21 118Z" fill="{a}"/>
 <path d="M87 40L54 74V118L85 153H985L1016 118V74L983 40L974 48H96Z" fill="url(#title)" stroke="{B}" stroke-width="16"/>
 <path d="M87 40L54 74V118L85 153H985L1016 118V74L983 40L974 48H96L87 40 M146 40H924 M17 48L48 17 M1022 17L1053 48" fill="none" stroke="{g}" stroke-width="8" stroke-linejoin="miter"/>
 <path d="M0 145H62V315L0 280Z M1070 145H1008V315L1070 280Z" fill="{B}"/>
 <path d="M22 169L45 183V274L22 260Z M1048 169L1025 183V274L1048 260Z" fill="{a}"/>
 <path d="M20 155L53 175V291L20 271 M1050 155L1017 175V291L1050 271" fill="none" stroke="{g}" stroke-width="8"/>
 <path d="M0 660L82 755H988L1070 660V875H0Z" fill="{B}"/>
 <path d="M22 686L82 755H988L1048 686" fill="none" stroke="{g}" stroke-width="8"/>
 <path d="M22 722L74 777H134L190 831H150L103 788H64L22 827Z M1048 722L996 777H936L880 831H920L967 788H1006L1048 827Z" fill="{a}"/>
 <path d="M0 830L62 791H104L150 839H920L966 791H1008L1070 830V1470H0Z" fill="#100f0b"/>
 <path d="M26 1215V837L66 799H100L146 843H924L970 799H1004L1044 837V1215" fill="none" stroke="{g}" stroke-width="8"/>
 <path d="M57 911L80 887H108L115 895H344L393 944H81L57 982Z" fill="url(#title)"/>
 <path d="M368 889L402 922H746L766 939" fill="none" stroke="{a}" stroke-width="6" stroke-linecap="round"/>
 <path d="M22 1215L53 1243V1294L87 1330V1341L42 1299V1255L22 1238Z M1048 1215L1017 1243V1294L983 1330V1341L1028 1299V1255L1048 1238Z" fill="{a}"/>
 <path d="M24 1268L38 1282V1365L70 1397H271L315 1350H755L799 1397H1000L1032 1365V1282L1046 1268 M87 1344H983" fill="none" stroke="{g}" stroke-width="8"/>
 <path d="M256 1358H295L277 1375Z M775 1358H814L793 1375Z" fill="{a}"/>
 <path d="M295 1398L329 1368H390 M775 1398L741 1368H680" fill="none" stroke="{a}" stroke-width="4"/>
 </svg>'''
 out=Image.alpha_composite(im.convert('RGBA'),Image.open(io.BytesIO(cairosvg.svg2png(bytestring=svg.encode()))).convert('RGBA')).convert('RGB')
 # Original glyphs and rules are pixel-preserved; never regenerated by AI.
 out.paste(im.crop((66,979,1005,1215)),(66,979));out.paste(im.crop((66,1215,1005,1318)),(66,1215))
 from PIL import ImageFilter
 edge=title.filter(ImageFilter.MaxFilter(7));out.paste(B,(100,55,980,136),edge);out.paste('white',(100,55,980,136),title)
 out.paste('white',(215,774,855,826),label)
 shadow=power.filter(ImageFilter.MaxFilter(9)).filter(ImageFilter.GaussianBlur(3));out.paste('#15110b',(85,892,350,944),shadow);out.paste('white',(85,892,350,944),power);d=ImageDraw.Draw(out)
 d.text((157,1377),str(n),font=ImageFont.truetype('DejaVuSans-Bold.ttf',36),fill='white',anchor='mm')
 font=ImageFont.truetype('DejaVuSans.ttf',26);word='DRAGON BALL';spacing=5;x=(1070-sum(font.getlength(ch) for ch in word)-spacing*(len(word)-1))/2
 for ch in word:d.text((x,1377),ch,font=font,fill='white',anchor='lm');x+=font.getlength(ch)+spacing
 assert out.crop((65,315,1005,680)).tobytes()==im.crop((65,315,1005,680)).tobytes()
 assert out.crop((88,980,1005,1318)).tobytes()==im.crop((88,980,1005,1318)).tobytes()
 # A single uniform fit adds the approved rounded outer margin.
 canvas=Image.new('RGB',(1070,1470),'#090d0e');inner=out.resize((1034,1420),Image.Resampling.LANCZOS);canvas.paste(inner,(18,20));mask=Image.new('L',(1070,1470));ImageDraw.Draw(mask).rounded_rectangle((9,10,1061,1460),radius=50,fill=255);return Image.composite(canvas,Image.new('RGB',canvas.size,'#100b09'),mask)
if __name__=='__main__':
 import argparse
 ap=argparse.ArgumentParser();ap.add_argument('--start',type=int,default=1);ap.add_argument('--end',type=int,default=70);args=ap.parse_args()
 catpath=R/'public/cards/catalog.js';txt=catpath.read_text();cs=json.loads(re.search(r'export const catalog\s*=\s*(\[.*?\]);',txt,re.S)[1]);entries=[]
 for c in cs:
  if not c['number'].isdigit() or not args.start<=int(c['number'])<=args.end:continue
  path=R/'public'/c['image'].split('?')[0].lstrip('/');im=Image.open(io.BytesIO(subprocess.check_output(['git','show','origin/main:'+str(path.relative_to(R))],cwd=R))).convert('RGB');out=render(im,c);tmp=path.with_suffix('.tmp.webp');out.save(tmp,'WEBP',lossless=True,method=4);tmp.replace(path)
  b=path.read_bytes();sha=hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest();txt=txt.replace(c['image'],c['image'].split('?')[0]+'?v='+sha[:10]);entries.append({'number':int(c['number']),'path':str(path.relative_to(R)),'sha':sha})
 catpath.write_text(txt);(R/'docs/saiyan-fixed-design.json').write_text(json.dumps({'updated':entries},indent=2)+'\n')
 print('Rendered',len(entries))
