import test from 'node:test';
import assert from 'node:assert/strict';
import {newGame, addPlayer, act, view, parseDeck, shuffle} from '../public/game.js';
const deck = prefix => ({personalities:[1,2,3].map(n=>({id:`${prefix}-MP-${n}`,pur:2})), cards:Array.from({length:17},(_,i)=>({id:`${prefix}-${i}`,qty:i===16?2:3}))});
function setup(){const g=newGame();addPlayer(g,'secret-a','Alice');addPlayer(g,'secret-b','Bob');act(g,0,{type:'load',deck:deck('A')});act(g,1,{type:'load',deck:deck('B')});act(g,0,{type:'start'});return g;}
function playing(){const g=setup();act(g,0,{type:'ready'});act(g,1,{type:'ready'});return g;}
test('Score setup has no opening hand, life pile, energy marker or mulligan',()=>{const g=setup();for(const p of g.players){assert.equal(p.zones.hand.length,0);assert.equal(p.zones.deck.length,50);assert.equal(p.stages,5);assert.equal(p.anger,0);assert.equal(p.level,1);assert.equal(p.zones.life,undefined);assert.equal(p.marker,undefined);}assert.throws(()=>act(g,0,{type:'mulligan'}));act(g,0,{type:'first',seat:1});act(g,0,{type:'ready'});act(g,1,{type:'ready'});assert.equal(g.turn,1);assert.equal(g.phase,'Draw');});
test('Draw three and damage use the Life Deck; opponent sees only hand counts',()=>{const g=playing();act(g,0,{type:'draw',count:3});act(g,0,{type:'damage'});assert.equal(g.players[0].zones.deck.length,46);assert.equal(g.players[0].zones.discard.length,1);const v=view(g,1);assert.deepEqual(v.players[0].zones.hand,{count:3});assert.ok(!JSON.stringify(v).includes('secret-a'));for(const c of g.players[0].zones.hand)assert.ok(!JSON.stringify(v).includes(c.uid));});
test('private Sensei choices swap together against original top cards exactly once',()=>{const g=newGame();addPlayer(g,'a','A');addPlayer(g,'b','B');const d=deck('A');d.sensei={id:'SENSEI'};d.senseiDeck=[{id:'SIDE-A'},{id:'SIDE-B'}];act(g,0,{type:'load',deck:d});act(g,1,{type:'load',deck:deck('B')});act(g,0,{type:'start'});const top=g.players[0].zones.deck.slice(0,2).map(c=>c.id),ids=g.players[0].zones.senseiDeck.map(c=>c.uid);assert.deepEqual(view(g,1).players[0].zones.senseiDeck,{count:2});act(g,0,{type:'senseiSwap',uids:ids});assert.deepEqual(g.players[0].zones.senseiDeck.map(c=>c.id),top);assert.equal(g.players[0].zones.deck.length,50);assert.ok(g.log.at(-1).text.includes('SIDE-A'));assert.throws(()=>act(g,0,{type:'senseiSwap',uids:g.players[0].zones.senseiDeck.map(c=>c.uid)}));});
test('phase branch skips Combat and permits one normal rejuvenation',()=>{const g=playing();act(g,0,{type:'damage'});for(let i=0;i<3;i++)act(g,0,{type:'phase'});assert.equal(g.phase,'Declare');assert.throws(()=>act(g,0,{type:'phase'}));act(g,0,{type:'phase',combat:false});assert.equal(g.phase,'Discard');act(g,0,{type:'phase'});act(g,0,{type:'rejuvenate'});assert.equal(g.players[0].zones.deck.length,50);assert.throws(()=>act(g,0,{type:'rejuvenate'}));act(g,0,{type:'phase'});assert.equal(g.turn,1);assert.equal(g.phase,'Draw');});
test('declared Combat blocks ordinary rejuvenation and opponent cannot advance steps',()=>{const g=playing();for(let i=0;i<3;i++)act(g,0,{type:'phase'});act(g,0,{type:'phase',combat:true});assert.equal(g.phase,'Combat');assert.throws(()=>act(g,1,{type:'phase'}));act(g,0,{type:'phase'});act(g,0,{type:'phase'});assert.throws(()=>act(g,0,{type:'rejuvenate'}));});
test('ownership prevents opponent card movement, Dragon Ball transfers are controller-only',()=>{const g=playing();act(g,0,{type:'draw'});const uid=g.players[0].zones.hand[0].uid;assert.throws(()=>act(g,1,{type:'move',from:'hand',to:'combat',uid}));act(g,0,{type:'move',from:'hand',to:'dragonballs',uid});assert.throws(()=>act(g,1,{type:'giveDragonBall',uid}));act(g,0,{type:'giveDragonBall',uid});assert.equal(g.players[1].zones.dragonballs.length,1);});
test('search and face-down cards are filtered; shuffle replaces tracking IDs',()=>{const g=playing();act(g,0,{type:'search'});assert.equal(view(g,1).players[0].searchCards,null);const uid=g.players[0].zones.deck[0].uid;act(g,0,{type:'move',from:'deck',to:'combat',uid});act(g,0,{type:'flip',from:'combat',uid});assert.deepEqual(Object.keys(view(g,1).players[0].zones.combat[0]).sort(),['faceDown','rested','uid']);const old=g.players[0].zones.deck.map(c=>c.uid);act(g,0,{type:'shuffle'});assert.equal(view(g,0).players[0].searchCards,null);assert.ok(g.players[0].zones.deck.every(c=>!old.includes(c.uid)));});
test('anger and MP level are manual, stage power-up uses PUR and Tokui-Waza',()=>{const g=playing();for(let i=0;i<6;i++)act(g,0,{type:'counter',counter:'anger',delta:1});assert.equal(g.players[0].anger,5);assert.equal(g.players[0].level,1);g.players[0].tokui='Red';act(g,0,{type:'powerUp'});assert.equal(g.players[0].stages,8);act(g,0,{type:'counter',counter:'level',delta:1});assert.equal(g.players[0].level,2);assert.equal(g.players[0].anger,5);});
test('Score import permits format exceptions with warnings; rejects old schema and invalid quantities',()=>{assert.throws(()=>parseDeck({leader:{id:'L'},cards:[]}));const d=deck('A');d.cards[0].qty=40;assert.equal(parseDeck(d).warnings.length>0,true);d.cards[0].qty=100;assert.throws(()=>parseDeck(d));const valid=deck('A');valid.personalities[0].image='javascript:alert(1)';assert.equal(parseDeck(valid).personalities[0].image,'');});
test('shuffle preserves card multiset and concession locks gameplay',()=>{const g=playing(),cards=g.players[0].zones.deck,ids=cards.map(c=>c.id).sort();shuffle(cards);assert.deepEqual(cards.map(c=>c.id).sort(),ids);act(g,0,{type:'concede'});assert.equal(g.winner,1);assert.throws(()=>act(g,1,{type:'draw'}));});

test('table positions validate ownership, survive hidden views, and clear on private moves',()=>{const g=playing();act(g,0,{type:'draw'});const uid=g.players[0].zones.hand[0].uid;act(g,0,{type:'move',from:'hand',to:'combat',uid});const a={type:'position',from:'combat',uid,position:{x:.6,y:.4}};act(g,0,a);assert.throws(()=>act(g,1,a));assert.throws(()=>act(g,0,{...a,position:{x:Infinity,y:0}}));act(g,0,{type:'flip',from:'combat',uid});const c=view(g,1).players[0].zones.combat[0];assert.deepEqual(c.position,a.position);assert.equal(c.id,undefined);act(g,0,{type:'move',from:'combat',to:'hand',uid});assert.equal(g.players[0].zones.hand[0].position,undefined);const mp=g.players[0].personalities[0];act(g,0,{type:'position',from:'mp',uid:mp.uid,position:{x:.2,y:.3}});act(g,0,{type:'position',from:'mp',uid:mp.uid,position:null});assert.equal(mp.position,null);});
