import {test,expect} from '@playwright/test';
test('digital rulebook stays local, searches expanded rules and works on mobile',async({page})=>{
  await page.goto('/');
  await expect(page.getByRole('link',{name:'Rulebook',exact:true})).toHaveAttribute('href','/rulebook/');
  await page.goto('/rulebook/');
  await expect(page.locator('h1')).toContainText('Know the rules');
  expect(await page.locator('.hero-card img').evaluate(i=>i.complete&&i.naturalWidth>0)).toBe(true);
  await expect(page.locator('a[href*="lackey"], iframe, object, embed')).toHaveCount(0);
  await expect(page.locator('[data-chapter]')).toHaveCount(17);
  await page.locator('#rule-search').fill('seventh');
  await expect(page.locator('#dragon-balls')).toBeVisible();
  await expect(page.locator('#dragon-balls details').last()).toHaveAttribute('open','');
  await page.locator('#rule-search').fill('no-rule-matches-this');
  await expect(page.locator('#no-results')).toBeVisible();
  await page.locator('#clear-search').click();
  await expect(page.locator('[data-chapter]:visible')).toHaveCount(17);
  await page.locator('#expand-rules').click();
  expect(await page.locator('details:not([open])').count()).toBe(0);
  await page.locator('#expand-rules').click();
  expect(await page.locator('details[open]').count()).toBe(0);
  await page.screenshot({path:'test-results/rulebook-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.locator('#rule-search').fill('rejuvenation');
  await expect(page.locator('#turn')).toBeVisible();
  await page.locator('.chapter-nav a[href="#setup"]').click();
  await expect(page.locator('#setup')).toBeVisible();
  await expect(page.locator('[data-chapter]:visible')).toHaveCount(17);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.locator('#rule-search').fill('endurance');
  await expect(page.locator('#endurance details').first()).toHaveAttribute('open','');
  await page.screenshot({path:'test-results/rulebook-mobile.png',fullPage:true});
  await page.evaluate(()=>window.dispatchEvent(new Event('beforeprint')));
  expect(await page.locator('details:not([open])').count()).toBe(0);
  await page.emulateMedia({media:'print'});
  await expect(page.locator('[data-chapter]:visible')).toHaveCount(17);
});
test('Physical Attack Table checks ratings, extremes and Z exception',async({page})=>{
  await page.goto('/rulebook/#damage');
  const a=page.locator('#pat-attacker'),d=page.locator('#pat-defender'),result=page.locator('#pat-result');
  await a.selectOption('4'); await d.selectOption('2');
  await expect(result).toHaveText('Base damage: 3 power stages');
  await expect(page.locator('.selected-damage')).toHaveText('3');
  await a.selectOption('0'); await d.selectOption('8');
  await expect(result).toHaveText('Base damage: 0 power stages');
  await a.selectOption('8'); await d.selectOption('0');
  await expect(result).toHaveText('Base damage: 8 power stages');
  await a.selectOption('9');
  await expect(result).toHaveText('Base damage: 2 power stages (Z rating)');
  await a.selectOption('0'); await d.selectOption('9');
  await expect(result).toHaveText('Base damage: 2 power stages (Z rating)');
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
